# Generated by Django 4.1.7 on 2023-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stdName", models.CharField(max_length=50)),
                ("stdId", models.CharField(max_length=10)),
                ("stdSex", models.CharField(default="M", max_length=50)),
                ("stdBirth", models.CharField(default="", max_length=50)),
                ("stdAddress", models.CharField(default="", max_length=255)),
                ("stdNumber", models.CharField(default="", max_length=10)),
                ("stdEmail", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
