# Generated by Django 4.1.7 on 2023-03-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="stdNumber", new_name="stdPhone",
        ),
        migrations.AlterField(
            model_name="student",
            name="stdBirth",
            field=models.DateField(default="", max_length=50),
        ),
    ]
