# Generated by Django 4.1.7 on 2023-03-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_rename_stdnumber_student_stdphone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="stdAddress",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="stdEmail",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="stdPhone",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
