# Generated by Django 4.2 on 2023-05-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bname", models.CharField(max_length=20)),
                ("bgender", models.CharField(default="F", max_length=2)),
                ("btitle", models.CharField(max_length=100)),
                ("bcontent", models.TextField()),
                ("btime", models.DateTimeField(auto_now=True)),
                ("bemail", models.EmailField(blank=True, default="", max_length=100)),
                ("bresponse", models.TextField(blank=True, default="")),
            ],
        ),
    ]
